{{- if and (not .Values.vpsie.existingSecret) .Values.vpsie.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vpsie-autoscaler.fullname" . }}-vpsie-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpsie-autoscaler.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ .Values.vpsie.clientId | b64enc | quote }}
  clientSecret: {{ .Values.vpsie.apiToken | b64enc | quote }}
  {{- if .Values.vpsie.apiURL }}
  url: {{ .Values.vpsie.apiURL | b64enc | quote }}
  {{- end }}
{{- end }}
